version: '3'
services:
    pickle:
        build: ./exploit/pickle/
        ports:
            - "9020:8000"
        command: -w 4 -b :8000 -u www-data -g www-data --access-logfile - app:app
        restart: always
