version: '2'
services:
 apache:
   image: vulhub/httpd:2.4-with-ssi
   ports:
    - "80:80"
   volumes:
    - ./upload.php:/var/www/html/upload.php
    - ./flag.txt:/var/www/html/youneverfindthispath/flag.txt
    - ./starwars:/var/www/html/
