version: '3'
services:
  can-you-see-1:
    container_name: can-you-see-1
    build: .
    image: tegshee/can-you-see-1
    ports:
      - "8001:80"
    volumes:
      - "./:/usr/local/apache2/htdocs"
    tty: true
